### ISSUE TITLE
AWS Stack

### ISSUE THREAD

**Issue by DomWifi** [awslabs/sagemaker-deep-demand-forecast#32]
Hi Folks, 
I'm trying to get this deep learning algorithm with aws sage maker to work but I am not able to generate the needed aws instance. When I use the link to create the stack, aws page opens and I can clikc the button Create Stack. But once the stack is created it deletes itself automatically (ROLLBACK_COMPLETE). 
I am new working with the SageMaker. Can anyone help me? Thanks
Dom

**Comment by ehsanmok** [comment]
Hi, thanks for your interest! What are the error messages before the rollback? You can find them in the Event section of the panel. I suspect that could be because of not available instances in your account. But to be sure I need more info about the errors.

**Comment by DomWifi** [comment]
Hi. Thanks for your quick response.

The status of CREATE_FAILED comes with the following error message:

Embedded stack arn:aws:cloudformation:us-west-2:226061980729:stack/sagemaker-soln-ddf-demand-SageMakerEndpointStack-15OQPRZKCE12E/e7ac4650-7a0e-11eb-8760-06025aea5659 was not successfully created: The following resource(s) failed to create: [Model].

And next Status ROLLBACK_IN_PROGRESS comes with this one:

The following resource(s) failed to create: [S3Bucket, SageMakerEndpointStack]. Rollback requested by user.

How can I make more instances available on my account?

Thanks
Dom

**Comment by DomWifi** [comment]
![image](https://user-images.githubusercontent.com/79811588/109435916-c1b62e80-79d1-11eb-8470-913195a286b9.png)

**Comment by ehsanmok** [comment]
Thanks for the details!

1. It seems your account doesn't have access to the ml.m5.xlarge instance to create the demo model. If you don't have admit access, please ask the admin of your account to grant you the access for ml.m5.xlarge instance. 
2. Please make sure there's no left over S3 buckets named sagemaker-soln-ddf- in your account. If you navigate in the console your can search for the buckets your account is using.

**Comment by DomWifi** [comment]
Hi!
Thanks for the response. I am in touch with aws right now to figure out why I don't have access to the m5.xlarge instance. I will keep you posted.

Dom

**Comment by ehsanmok** [comment]
Closing this issue now. Please feel free to reopen it if you encounter any issue.
